version: "3"

services:
  tsc-express-api:
    build: 
      context: ./
      dockerfile: Dockerfile-debug
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - "9000:5000"
    depends_on: 
      - mongo 
    command: "npm run dev"

  mongo:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    volumes: 
      - db-data
volumes: 
  db-data: