version: "3"

services:
  tsc-express-api:
    build: 
      context: ./
      dockerfile: Dockerfile-debug
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - "9000:5000"
    depends_on: 
      - mongodb

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
