version: "3"

services:
  tsc-express-api:
    image: tsc-express
    build: 
      context: ./
      dockerfile: Dockerfile
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - "9000:9000"
    depends_on: 
      - mongo 

  mongo:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"